sudo: false
language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages

addons:
  apt:
    packages:
      - libhdf5-serial-dev

install:
  - "pip install -r requirements.txt"
  
# command to run tests
script:
    - for filename in examples/*.nxs; do echo "==========  $filename ==========";python src/nxfeature.py -t "$filename"; done
